#!/usr/bin/env node
/**
 * HCIG Studio: check the built site.
 *
 *   node check.js        (run after a build; `npm test` does both)
 *
 * A build that succeeds is not the same as a site that works. This walks
 * everything in dist/ and fails on the things a quick look would miss:
 *
 *   - an internal link that goes nowhere
 *   - a missing asset, stylesheet or script
 *   - "undefined", "NaN" or "[object Object]" leaking into the page
 *   - an unresolved %%TOKEN%%
 *   - a page with no <h1>, no <main>, or more than one <h1>
 *   - an image with no alt attribute
 *   - an external link opened in a new tab without rel="noopener"
 */

const fs = require('fs');
const path = require('path');

const DIST = path.join(__dirname, 'dist');
const problems = [];
const notes = [];

if (!fs.existsSync(DIST)) {
  console.error('\n  dist/ not found - run `npm run build` first.\n');
  process.exit(1);
}

/* --------------------------------------------------------------- walking */

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, e.name);
    if (e.isDirectory()) walk(abs, out);
    else out.push(abs);
  }
  return out;
}

const files = walk(DIST);
const htmlFiles = files.filter((f) => f.endsWith('.html'));
const rel = (abs) => abs.slice(DIST.length).replace(/\\/g, '/');

/* Production also honours the redirects in vercel.json, so the checker has to
   know about them or it reports a working URL as dead. */
const REDIRECTS = new Set(
  (JSON.parse(fs.readFileSync(path.join(__dirname, 'vercel.json'), 'utf8')).redirects || []).map((r) => r.source)
);

/** Mirror Vercel's cleanUrls + directory index, so the checker resolves a URL
 *  the same way production will. */
function resolves(url) {
  const clean = url.split('#')[0].split('?')[0];
  if (!clean || clean === '/') return fs.existsSync(path.join(DIST, 'index.html'));
  if (REDIRECTS.has(clean)) return true;
  const p = path.join(DIST, clean.replace(/^\/+/, ''));
  if (fs.existsSync(p) && fs.statSync(p).isFile()) return true;
  if (fs.existsSync(p + '.html')) return true;
  if (fs.existsSync(path.join(p, 'index.html'))) return true;
  return false;
}

const bad = (file, msg) => problems.push(`${rel(file)}  ${msg}`);

/* ---------------------------------------------------------------- checks */

for (const file of htmlFiles) {
  const html = fs.readFileSync(file, 'utf8');

  for (const leak of ['undefined', 'NaN', '[object Object]']) {
    // only flag it as page text or an attribute value, not inside a script
    const stripped = html.replace(/<script[\s\S]*?<\/script>/gi, '');
    if (stripped.includes(leak)) bad(file, `leaked "${leak}" into the page`);
  }

  const stray = html.match(/%%[A-Z0-9_]+%%/g);
  if (stray) bad(file, `unresolved token ${[...new Set(stray)].join(', ')}`);

  /* Portal pages are generated by this repo and held to its structure. The
     self-contained design documents are served as authored, so only the safety
     checks apply to them. */
  const isPortal = html.includes('/studio.css');

  if (isPortal) {
    const h1 = html.match(/<h1[\s>]/g) || [];
    if (h1.length === 0) bad(file, 'no <h1>');
    if (h1.length > 1) bad(file, `${h1.length} <h1> elements, expected one`);
    if (!/<main[\s>]/.test(html)) bad(file, 'no <main> landmark');
    if (!/class="skip"/.test(html)) bad(file, 'no skip link');
  }

  // attribute values may legitimately be unquoted, so do not require quotes
  if (!/<html[^>]*\slang=/i.test(html)) bad(file, 'no lang on <html>');
  if (!/<meta[^>]+name=["']?viewport["']?/i.test(html)) bad(file, 'no viewport meta');
  if (!/<meta[^>]+name=["']?robots["']?[^>]*noindex/i.test(html)) bad(file, 'not served noindex');

  // images must carry an alt attribute, even an empty decorative one
  for (const tag of html.match(/<img\b[^>]*>/gi) || []) {
    if (!/\balt=/.test(tag)) bad(file, `img with no alt: ${tag.slice(0, 90)}`);
  }

  // links and referenced files
  for (const m of html.matchAll(/\b(?:href|src)="([^"]+)"/g)) {
    const url = m[1];
    if (/^(https?:|data:|mailto:|tel:|#|\/\/)/.test(url)) continue;
    if (!url.startsWith('/')) {
      notes.push(`${rel(file)}  relative URL "${url}" (root-absolute is safer at depth)`);
      continue;
    }
    if (!resolves(url)) bad(file, `dead link ${url}`);
  }

  // a new tab without rel="noopener" hands the opener to the other page
  for (const tag of html.match(/<a\b[^>]*target="_blank"[^>]*>/gi) || []) {
    if (!/rel="[^"]*noopener/.test(tag)) bad(file, `target=_blank without noopener: ${tag.slice(0, 90)}`);
  }
}

/* --------------------------------------------------------------- report */

console.log(`\n  Checked ${htmlFiles.length} pages, ${files.length} files in dist/\n`);

if (notes.length) {
  console.log('  Notes');
  for (const n of [...new Set(notes)]) console.log(`    ${n}`);
  console.log('');
}

if (problems.length) {
  console.log('  Problems');
  for (const p of problems) console.log(`    ${p}`);
  console.log(`\n  ${problems.length} problem${problems.length === 1 ? '' : 's'}. Not shippable.\n`);
  process.exit(1);
}

console.log('  No problems.\n');
