#!/usr/bin/env node
/**
 * MedPark: generate sitemap.xml from the hreflang map.
 *
 * The old sitemap listed 15 URLs, all English. The German and Polish pages
 * appeared only as <xhtml:link rel="alternate"> annotations inside those
 * entries, never as a <loc> of their own, and there was no x-default anywhere.
 * Google can still find a page that way, but it is weaker than listing it, and
 * German and Polish are the two markets we are trying to grow.
 *
 * Rather than hand-maintain a second list that drifts, this reads the single
 * source of truth, medpark-live/hreflang.php, where every URL was verified to
 * return 200 before it was added. Every language version becomes its own <loc>
 * carrying the full alternate set, including itself and x-default.
 *
 *   node scripts/medpark-sitemap.js            write medpark-live/sitemap.xml
 *   node scripts/medpark-sitemap.js --check    print what it would write
 *
 * English-only pages that have no translation are listed below by hand, with
 * no alternates. A page with no translation must not claim to have one.
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const HREFLANG = path.join(ROOT, 'medpark-live', 'hreflang.php');
const OUT = path.join(ROOT, 'medpark-live', 'sitemap.xml');
const SITE = 'https://www.medparkhospitals.com';

/**
 * Pages that exist in English only. They get a <loc> and no alternates.
 * Add here, not to the hreflang map: that map is for pages with translations.
 */
const ENGLISH_ONLY = [
  { path: '/hospitals-in-hurghada/', priority: '0.9', changefreq: 'weekly' },
];

/** Priority and change frequency by shape of the path. */
function weightFor(enPath) {
  if (enPath === '/') return { priority: '1.0', changefreq: 'weekly' };
  if (/\/news\d*\.php$/.test(enPath)) return { priority: '0.5', changefreq: 'monthly' };
  if (/^\/news\/$/.test(enPath)) return { priority: '0.6', changefreq: 'weekly' };
  return { priority: '0.8', changefreq: 'monthly' };
}

/**
 * Pull the rows out of hreflang.php.
 * Each row looks like: array('en' => '/x/', 'de' => '/y/', 'pl' => '/z/'),
 */
function readMap() {
  const php = fs.readFileSync(HREFLANG, 'utf8');
  const body = php.slice(php.indexOf('function mp_hreflang_map'), php.indexOf('function mp_current_path'));
  const rows = [];
  const re = /array\(\s*'en'\s*=>\s*'([^']+)'\s*,\s*'de'\s*=>\s*'([^']*)'\s*,\s*'pl'\s*=>\s*'([^']*)'\s*\)/g;
  let m;
  while ((m = re.exec(body)) !== null) {
    rows.push({ en: m[1], de: m[2] || null, pl: m[3] || null });
  }
  if (rows.length === 0) throw new Error('No rows parsed from hreflang.php. Did its format change?');
  return rows;
}

const xml = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** One <url> block: this page, with every alternate including itself. */
function urlBlock(loc, row, weight) {
  const lines = [
    '  <url>',
    `    <loc>${xml(SITE + loc)}</loc>`,
    `    <changefreq>${weight.changefreq}</changefreq>`,
    `    <priority>${weight.priority}</priority>`,
  ];
  if (row) {
    for (const [code, key] of [['en', 'en'], ['de', 'de'], ['pl', 'pl']]) {
      if (!row[key]) continue;
      lines.push(`    <xhtml:link rel="alternate" hreflang="${code}" href="${xml(SITE + row[key])}"/>`);
    }
    // x-default is what a visitor gets when we do not serve their language.
    lines.push(`    <xhtml:link rel="alternate" hreflang="x-default" href="${xml(SITE + row.en)}"/>`);
  }
  lines.push('  </url>');
  return lines.join('\n');
}

function build() {
  const rows = readMap();
  const blocks = [];
  let counts = { en: 0, de: 0, pl: 0, only: 0 };

  for (const row of rows) {
    const weight = weightFor(row.en);
    for (const key of ['en', 'de', 'pl']) {
      if (!row[key]) continue;
      blocks.push(urlBlock(row[key], row, weight));
      counts[key]++;
    }
  }
  for (const p of ENGLISH_ONLY) {
    blocks.push(urlBlock(p.path, null, p));
    counts.only++;
  }

  const head = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/medpark-sitemap.js from medpark-live/hreflang.php.
     Do not edit by hand: regenerate it, or the sitemap and the hreflang tags
     will disagree and Google will trust neither.
     Every language version is its own <loc> with the full alternate set,
     including itself and x-default. Last generated ${new Date().toISOString().slice(0, 10)}. -->
<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xhtml="http://www.w3.org/1999/xhtml">

`;
  return { xml: head + blocks.join('\n\n') + '\n\n</urlset>\n', counts, total: blocks.length };
}

function main() {
  const { xml: out, counts, total } = build();
  if (process.argv.includes('--check')) {
    console.log(out.slice(0, 1200));
    console.log(`  ... ${total} url blocks`);
    return;
  }
  fs.writeFileSync(OUT, out);
  console.log(`  sitemap.xml written: ${total} <loc> entries`);
  console.log(`    English ${counts.en}, German ${counts.de}, Polish ${counts.pl}, English-only ${counts.only}`);
  console.log(`    was 15 entries, all English, with no x-default`);
}

if (require.main === module) main();
module.exports = { build, readMap };
